# Lint project Sass files via Sass-Lint.
# More info - https://github.com/sasstools/sass-lint.
# More info - https://github.com/sasstools/grunt-sass-lint.


options:
  # Don't merge default rules.
  merge-default-rules: false
  # Set the formatter.
  formatter: stylish

files:
  include: '**/*.s+(a|c)ss'

rules:

  # Enforce whether one should use 0 or none when specifying a zero border value.
  border-zero: 1

  # Enforce the use of the chosen brace style.
  brace-style:
    - 1
    - style: '1tbs' # options: '1tbs', 'stroustrup', 'allman'
    - allow-single-line: true

  # Enforce whether or not @import paths should have leading underscores and/or filename extensions.
  clean-import-paths: 1

  # Enforce whether or not parenthesis should be included if no arguments are defined or used, when declaring or invoking a mixin.
  empty-args: 1

  # Enforce whether or not nested blocks should include a space between the last non-comment declaration or not.
  empty-line-between-blocks: 1

  # Enforce that extends should be written before declarations in a ruleset.
  extends-before-declarations: 1

  # Enforce that extends should be written before mixins in a ruleset.
  extends-before-mixins: 1

  # Enforce whether or not files should end with a newline.
  final-newline: 1

  # Enforce the nesting of attributes.
  force-attribute-nesting: 0

  # Enforce the nesting of elements.
  force-element-nesting: 0

  # Enforce the nesting of pseudo elements/classes.
  force-pseudo-nesting: 0

  # Enforce the length of hexadecimal values.
  hex-length:
    - 1
    - style: long

  # Enforce an indentation size (in spaces) and ensure that tabs and spaces are not mixed.
  indentation:
    - 1
    - size: 4

  # Enforce whether or not decimal numbers should include a leading zero.
  leading-zero:
    - 1
    - include: true

  # Enforce how deeply a selector can be nested.
  nesting-depth:
    - 1
    - max-depth: 3

  # Enforce the use of Sass single-line comments and disallow CSS comments.
  no-css-comments: 0

  # Enforce that ID selectors are not allowed to be used.
  no-ids: 0

  # Enforce that important declarations are not allowed to be used.
  no-important: 0

  # Enforce that selectors are not allowed to have qualifying elements.
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: true
    - allow-element-with-class: true
    - allow-element-with-id: false

  # Enforce the order in which declarations are written.
  property-sort-order:
    - 1
    - order: 'smacss' # options: 'alphabetical', 'concentric', 'recess', 'smacss', or [array of properties].

  # Enforce whether single quotes or double quotes should be used for all strings.
  quotes:
    - 1
    - style: double
